### ISSUE TITLE
[RFE] Should support user specify spec.nodeName in pod yaml

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes-incubator/cluster-capacity#19]
Pod should be scheduled to specify node follow spec.nodeName in pod yaml, and will not be scheduled to other nodes.

Such as below pod only can be scheduled to `ec2-54-161-105-73.compute-1.amazonaws.com`, but in current code doesn't support this feature. Furthermore, the pod with `spec.nodeName` also can be scheduled to a paint or unschedulable node. You can refer to my TC: https://tcms-openshift.rhcloud.com/case/6053/?from_plan=

```
# cat nodename-pod1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: small-pod1
  namespace: cluster-capacity
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
  - name: php-redis
    image: gcr.io/google-samples/gb-frontend:v4
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 100Mi
  restartPolicy: "OnFailure"
  dnsPolicy: "Default"
  nodeName: ec2-54-161-105-73.compute-1.amazonaws.com
```
```
# cc --podspec nodename-pod1.yaml
E1205 01:24:41.024684   17369 factory.go:583] Error scheduling cluster-capacity small-pod-17: pod (small-pod-17) failed to fit in any node
fit failure on node (ec2-54-158-106-111.compute-1.amazonaws.com): Insufficient cpu
fit failure on node (ec2-54-161-105-73.compute-1.amazonaws.com): Insufficient cpu
; retrying
The cluster can schedule 17 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-17) failed to fit in any node
```
