### ISSUE TITLE
Report capacity as a metric

### ISSUE THREAD

**Issue by aweiteka** [kubernetes-incubator/cluster-capacity#93]
As a cluster administrator I rely on prometheus metrics and alert manager rules to automate responding to cluster events. I want cluster capacity results to be exposed as a metric so I can alert operations and respond. Example metric:

```
# HELP cluster_capacity_schedulable_count number schedulable pods
# TYPE cluster_capacity_schedulable_count gauge
cluster_capacity_schedulable_count{podspec="basic_user_pod.yaml"} 23
cluster_capacity_schedulable_count{podspec="infra.yaml"} 1
```

With this data I am able create a rule like this to automate a response:

```
    - alert: MaxCapacityInfra
      expr: cluster_capacity_schedulable_count{podspec="infra.yaml"} < 2
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "Insufficient node capacity given for podspec {{ $labels.podspec }}"
        auto_heal: true
        auto_heal_playbook: playbooks/infra_node_scaleout.yml
```

Reference: https://prometheus.io/docs/instrumenting/

cc @aveshagarwal @derekwaynecarr @eparis
